### PR TITLE
#120T Fix List builder not responding as expected during LOQ

### PR DESCRIPTION
**Pull request by nmadruga**
Fix Templates [issue #120](https://github.com/openmsupply/conforma-templates/issues/120)

- Added type to `parameters` received in ApplicationView of listBuilder
- Prevent bug by adding `isRequired` to `ListItem` type received 
- Now `anyIncompleteItems` helper function doesn't receive 2 separated lists (that were getting inconsistent)

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Cool, I'll check this out over the weekend or on Monday. Thanks

**Comment by CarlosNZ** [comment]
@nmadruga would you mind providing a snapshot where we can see this without having to go through the whole application/review process?

**Comment by nmadruga** [comment]
Sent on dm. Steps to recreate. Log in as: user test/EXT1234
Find the application of `CPR-0013-2023` with Changes requested
Try to edit just the line requested and resubmit.

**Comment by nmadruga** [comment]
Closed after simpler fix is done by Carl

**Pull request closed without merging**
